# Metody analizy danych. Lab 3. Biblioteka numpy, część 3

## 1. Wybrane operacje arytmetyczne na tablicy numpy

In [1]:
import numpy as np

In [2]:
# funkcje zaczerpnięte z https://tobiasraabe.github.io/post/numpy-views-vs-copies/
# dzięki nim łatwiej będzie nam interpretować czy dwie tablice numpy posiadają wspólną bazę
# co oznacza, że współdzielą pamięć (lub nie)

def get_data_base(x):
    base = x
    while isinstance(base.base, np.ndarray):
        base = base.base
    return base

def arrays_share_data(x, y):
    return get_data_base(x) is get_data_base(y)

In [3]:
arr = np.arange(1,101).reshape((10,10))
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [4]:
# suma wartości elementów tablicy
print(arr.sum())
# lub
print(np.sum(arr))

5050
5050


In [5]:
# suma w kolumnach (indeks po wierszach)
print(arr.sum(axis=0))
# i w wierszach (indeks po kolumnach)
print(arr.sum(axis=1))

[460 470 480 490 500 510 520 530 540 550]
[ 55 155 255 355 455 555 655 755 855 955]


In [6]:
# suma skumulowana
print(arr.cumsum())

[   1    3    6   10   15   21   28   36   45   55   66   78   91  105
  120  136  153  171  190  210  231  253  276  300  325  351  378  406
  435  465  496  528  561  595  630  666  703  741  780  820  861  903
  946  990 1035 1081 1128 1176 1225 1275 1326 1378 1431 1485 1540 1596
 1653 1711 1770 1830 1891 1953 2016 2080 2145 2211 2278 2346 2415 2485
 2556 2628 2701 2775 2850 2926 3003 3081 3160 3240 3321 3403 3486 3570
 3655 3741 3828 3916 4005 4095 4186 4278 4371 4465 4560 4656 4753 4851
 4950 5050]


In [7]:
# i ponownie możemy wykonać operację dla danej osi
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 12  14  16  18  20  22  24  26  28  30]
 [ 33  36  39  42  45  48  51  54  57  60]
 [ 64  68  72  76  80  84  88  92  96 100]
 [105 110 115 120 125 130 135 140 145 150]
 [156 162 168 174 180 186 192 198 204 210]
 [217 224 231 238 245 252 259 266 273 280]
 [288 296 304 312 320 328 336 344 352 360]
 [369 378 387 396 405 414 423 432 441 450]
 [460 470 480 490 500 510 520 530 540 550]]
[[  1   3   6  10  15  21  28  36  45  55]
 [ 11  23  36  50  65  81  98 116 135 155]
 [ 21  43  66  90 115 141 168 196 225 255]
 [ 31  63  96 130 165 201 238 276 315 355]
 [ 41  83 126 170 215 261 308 356 405 455]
 [ 51 103 156 210 265 321 378 436 495 555]
 [ 61 123 186 250 315 381 448 516 585 655]
 [ 71 143 216 290 365 441 518 596 675 755]
 [ 81 163 246 330 415 501 588 676 765 855]
 [ 91 183 276 370 465 561 658 756 855 955]]


In [8]:
# na potrzeby kilku przykładów wykorzystamy kopię oryginalnej tablicy
arr_nan = arr.copy()

In [9]:
# filtrowanie tablicy zwraca tablicę boolowską - mapę - wartości, które spełniają i nie spełniają warunku
divide_by_five_map = (arr_nan % 5 == 0)
divide_by_five_map

array([[False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True]])

In [10]:
# będziemy też od czasu do czasu sprawdzać czy pracujemy na kopii czy widoku
# tu mamy do czynienia z tzw. fancy slicing - więc kopia
arrays_share_data(arr_nan, divide_by_five_map)

False

In [11]:
# taką tablicę możemy przyłożyć do innej tablicy (uwaga na wymiary!)
divide_by_five = arr_nan[divide_by_five_map]
divide_by_five

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [12]:
arrays_share_data(divide_by_five, arr_nan)

False

In [13]:
# zamieniamy wartości stojące na indeksach z mapy na wartość np.nan (not a number)
arr_nan[divide_by_five_map] = np.nan

ValueError: cannot convert float NaN to integer

In [37]:
arr_nan

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [38]:
arr_nan.dtype

dtype('int64')

In [39]:
# okazuje się, że dla typu np.int nie możemy tego zrobić
# może dla np.float
# po nieudanej operacji wstawienia nan należy sprawdzić czy tablica zawiera poprawne dane
# jeżeli nie to operację stworzenia kopii należy wykonać jeszcze raz
arr_nan = arr_nan.astype(np.float64)
arr_nan

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [41]:
arr_nan[divide_by_five_map] = np.nan

In [40]:
# wykonajmy ponownie operację sumy
print(arr_nan.sum())

5050.0


In [42]:
print(arr_nan.sum(axis=0))
print(arr_nan.sum(axis=1))

[460. 470. 480. 490.  nan 510. 520. 530. 540.  nan]
[nan nan nan nan nan nan nan nan nan nan]


In [43]:
# jeżeli chcemy potraktować wartości nan w jakiś szczególny sposób, np. jako 0 (zero) to mamy do
# dyspozycji dedykowane funckje - tu sumy
print(np.nansum(arr_nan))
print(np.nansum(arr_nan, axis=0))
print(np.nansum(arr_nan, axis=1))

4000.0
[460. 470. 480. 490.   0. 510. 520. 530. 540.   0.]
[ 40. 120. 200. 280. 360. 440. 520. 600. 680. 760.]


In [44]:
# mnożenie elementów tablicy
# nie działa? dlaczego 0 ? Tu następuje przepełnienie wartości dla typów obsługiwanych przez numpy.
# Typ int wbudowany w Python może być niezwykle dużą liczbą (pamięć operacyjna nas ogranicza), ale  numpy
# opieramy się o typy znane z języka C. Przepełnienie wartości np.int64 czy np.float64 przy mnożeniu może
# nastąpić bardzo szybko. I tu zwracane jest 0 bez żadnego ostrzeżenia - trzeba o tym pamiętać.
print(arr.prod())
print(arr.prod(axis=0))

0
[19511273389031424  2394832584543399  1242688846823424   478015854767451
 26853950884211451 13865696119905399  6393838623046875  9585618768101376
  4060162871525376 36288000000000000]


In [46]:
# numpy posiada bardzo wiele wbudowanych funkcji arytmetycznych, trygonometrycznych, algebry liniowej i innych.
# Algebrą liniową zajemy się nieco później. Poniżej kilka przykładów innych, popularnych operacji.
print(arr.max(), arr.max(axis=0))

100 [ 98  93  92  91  99  97  95  96  94 100]


In [45]:
# możemy również wykorzystać operacje tego typu do filtrowania tablicy
arr[(arr == arr.max(axis=0))]

array([ 98,  93,  92,  91,  99,  97,  95,  96,  94, 100])

In [47]:
# tu warto przedstawić również funkcję np.where, która zamiast zwracać wartości spełniające warunek,
# może zwracać indeksy, na których te warunki są spełnione. Poniżej zobaczymy dwie tablice, gdyż talica, w
# której filtrujemy jest dwuwymiarowa. Pierwszy wymiar to wiersz, a drugi kolumna.
# Funkcja np.where przyjmuje do trzech argumentów: warunek, x, y. Jeżeli podany jest tylko warunek to zwraca indeksy elementów
# spełniających ten warunek.

In [48]:
np.where(arr == arr.max(axis=0))

(array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [49]:
# co jest ekwiwalentem
np.asarray(arr == arr.max(axis=0)).nonzero()

(array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [50]:
# ale możemy ją wykorzystać również w taki sposób
# warunek, wartość jeżeli warunek spełniony, wartość jeżeli warunek nie jest spełniony
np.where(arr == arr.max(axis=0), arr, np.nan)

array([[ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ 98.,  93.,  92.,  91.,  99.,  97.,  95.,  96.,  94., 100.]])

## 2. Moduł np.random

Moduł `np.random` dostarcza wielu funkcji, które pozwalają zarówno na tworzenie tablic wartości losowych (bardziej precyzyjnie to pseudo-losowych, ze zwględu na sposób działania komputerów) o określonych właściwościach, ale również na próbkowaniu z tablic już istniejących.

### 2.1 Tworzenie tablic z wykorzystaniem wybranych elementów modułu np.random

Korzystanie z modułu rozpoczynamy od inicjalizacji generatowa pseudolosowego.

In [51]:
rng = np.random.default_rng()

In [52]:
rng.random()

0.26793025967824546

In [53]:
rng.random((5,5))

array([[0.23221679, 0.09603316, 0.61836834, 0.85861878, 0.26705704],
       [0.51777661, 0.6564873 , 0.46100112, 0.008728  , 0.06036491],
       [0.44344988, 0.13903644, 0.4798906 , 0.48904053, 0.37897725],
       [0.07856177, 0.20218327, 0.05597467, 0.08183388, 0.65060866],
       [0.38078919, 0.06910981, 0.75575082, 0.08953518, 0.95472878]])

In [17]:
# wartości są zwracane z przedziału [0.0, 1.0)

In [18]:
# możemy próbkować wartości pseudolosowe z rozkładów, np. normalnego
# sygnatura tej funkcji: normal(loc=0.0, scale=1.0, size=None) (średnia, odchylenie standardowe, rozmiar)
print(rng.normal())
print(rng.normal(size=(5,5)))

-0.15427618089642667
[[ 0.64094123 -0.08654991 -1.40503896 -0.75149033 -2.92124331]
 [-1.14652872 -0.55642406  0.41381295 -0.89098961  0.24863157]
 [-0.62390604 -1.57479669  0.30968447  0.35428195  0.58550647]
 [-0.66437409  1.67696624 -0.47963816 -0.51252662 -0.73924418]
 [-0.7348027   1.7047587   1.82738202  0.25222121  0.13562612]]


In [19]:
# lub możemy użyć poniższej funkcji (mean=0.0, std=1.0)
rng.standard_normal(5)

array([ 2.10330808,  0.57381047,  0.08554318,  0.81230894, -0.20596671])

In [20]:
# generowanie wartości całkowitych z przedziału
rng.integers(low=1, high=100, size=10)

array([ 9, 52, 31, 27, 79, 55, 55, 79, 51, 66])

In [21]:
# choice - pobiera losową próbkę danych z tablicy
# sygnatura: choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)
# Parametr p pozwala na przekazanie tablicy z rozkładem prawdopodobieństw

In [22]:
# zwróć uwagę na output: zwracany jest losowy wiersz
rng.choice(arr)

array([81, 82, 83, 84, 85, 86, 87, 88, 89, 90])

In [23]:
# domyślnie wybór odbywa się ze zwracaniem (replace=True)
rng.choice(arr, size=20)

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70

In [24]:
rng.choice(arr, size=5, replace=False)

array([[41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [25]:
# a gdybyśmy jednak chcieli losować po pojedynczej wartości tablicy?
# możemy wykorzystać funkcje poznane w poprzednim labie
rng.choice(arr.flat, size=10, replace=False)

array([54, 55, 41,  8,  3, 28, 92, 32, 14, 34])

In [26]:
# "tasowanie" tablicy odbywa się w trybie in-place
rng.shuffle(arr)
arr

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [27]:
# oraz domyślnie axis=0, ale możemy to zmienić
rng.shuffle(arr, axis=1)
arr

array([[ 48,  43,  42,  41,  49,  47,  45,  46,  44,  50],
       [ 28,  23,  22,  21,  29,  27,  25,  26,  24,  30],
       [ 68,  63,  62,  61,  69,  67,  65,  66,  64,  70],
       [ 88,  83,  82,  81,  89,  87,  85,  86,  84,  90],
       [ 58,  53,  52,  51,  59,  57,  55,  56,  54,  60],
       [ 78,  73,  72,  71,  79,  77,  75,  76,  74,  80],
       [  8,   3,   2,   1,   9,   7,   5,   6,   4,  10],
       [ 18,  13,  12,  11,  19,  17,  15,  16,  14,  20],
       [ 38,  33,  32,  31,  39,  37,  35,  36,  34,  40],
       [ 98,  93,  92,  91,  99,  97,  95,  96,  94, 100]])

In [28]:
# uzyskanie permutacji z tablicy lub podając integer (działa w wiekszości podobnych funkcji numpy)
# zwraca permutację liczb całkowitych z zakresu.
# Główna różnica między shuffle a permutation jest taka, iż pierwsza operacja odbywa się w trybie in-place
# a druga zwraca kopię
rng.permutation(10)

array([9, 8, 3, 0, 6, 1, 2, 7, 4, 5])

In [29]:
rng.permutation(arr)

array([[ 18,  13,  12,  11,  19,  17,  15,  16,  14,  20],
       [ 48,  43,  42,  41,  49,  47,  45,  46,  44,  50],
       [ 98,  93,  92,  91,  99,  97,  95,  96,  94, 100],
       [  8,   3,   2,   1,   9,   7,   5,   6,   4,  10],
       [ 78,  73,  72,  71,  79,  77,  75,  76,  74,  80],
       [ 38,  33,  32,  31,  39,  37,  35,  36,  34,  40],
       [ 68,  63,  62,  61,  69,  67,  65,  66,  64,  70],
       [ 28,  23,  22,  21,  29,  27,  25,  26,  24,  30],
       [ 88,  83,  82,  81,  89,  87,  85,  86,  84,  90],
       [ 58,  53,  52,  51,  59,  57,  55,  56,  54,  60]])

## 2.2 Zapis i odczyt tablic z plików

In [30]:
# zapisanie danych do pliku tekstowego
np.savetxt('arr.txt', arr)

In [31]:
# windows - odczyt zawartości zapomocą polecenia powłoki systemowej
!type arr.txt
# unix lub windows z WSL
# !cat arr.txt

/bin/bash: line 1: type: arr.txt: not found


In [32]:
# dodajemy format
np.savetxt('arr.txt', arr, fmt='%.1f')

In [33]:
!type arr.txt

/bin/bash: line 1: type: arr.txt: not found


In [34]:
# wczytanie danych z pliku (ta funkcja posiada wiele parametrów mających wpływ na sposób wczytywania danych)
arr_from_file = np.loadtxt('arr.txt')

In [35]:
print(arr_from_file, arr_from_file.dtype)

[[ 48.  43.  42.  41.  49.  47.  45.  46.  44.  50.]
 [ 28.  23.  22.  21.  29.  27.  25.  26.  24.  30.]
 [ 68.  63.  62.  61.  69.  67.  65.  66.  64.  70.]
 [ 88.  83.  82.  81.  89.  87.  85.  86.  84.  90.]
 [ 58.  53.  52.  51.  59.  57.  55.  56.  54.  60.]
 [ 78.  73.  72.  71.  79.  77.  75.  76.  74.  80.]
 [  8.   3.   2.   1.   9.   7.   5.   6.   4.  10.]
 [ 18.  13.  12.  11.  19.  17.  15.  16.  14.  20.]
 [ 38.  33.  32.  31.  39.  37.  35.  36.  34.  40.]
 [ 98.  93.  92.  91.  99.  97.  95.  96.  94. 100.]] float64


In [36]:
# ten format jest oczywiście wygodny dla człowieka i dane często są dostarczane w takiej formie
# jednak nie jest to sposób najbardziej wydajny z dostępnych.
# Tutaj pokażę tylko jedną z możliwości, ale dla poszerzenia wiedzy można zainteresować się formatami
# danych wykorzystywanymi w zagadnieniach Big Data.
np.save('arr_pickle', arr)

## Zadania


1. Stwórz tablicę o nazwie `a_small_one` o wymiarach 8x8 z wartościami od 1 do 64.

2. Dla tablicy `a_small_one` policz:
   * sumę dla każdej kolumny,
   * sumę skumulowaną dla każdego wiersza,
   * wartość średnią dla każdego wiersza,

3. Zwróć podtablicę z tablicy `a_small_one` z elementami parzystymi (nie nadpisuj tej zmiennej).

4. Zapisz do zmiennej o nazwie `no_even_small_one` tablicę `a_small_one` zamieniając wartości parzyste na wartość np.nan.

5. Dla tablicy `no_even_small_one` policz funkcjami uwzględniającymi wartości nan (zazwyczaj posiadają przedrostek nan):
   * sumę dla każdego wiersza,
   * średnią dla każdej kolumny,
   * wartość najmniejszą w całej tablicy,

6. Do tablicy `no_even_small_one` wstaw za pomocą funkcji `np.where`:

   * wartości 1 dla każdej wartości np.nan (zobacz wbudowaną funkcję `np.isnan()`)
   * liczby parzyste, które wcześniej zastąpiliśmy wartościami nan (teraz 1 jeżeli wykonany jest podpunkt pierwszy), więc przywracamy ten tablicy wygląd oryginalny z tablicy `a_small_one` - dla warunku wstawiaj wartość z `a_small_one` lub `no_even_small_one`

7. Stwórz tablicę o nazwie `sto_by_sto` o wymiarach 100x100 próbkując wartości z rozkładu normalnego standardowego.

8. Dla tablicy `sto_by_sto` policz:
   * wartość średnią w każdym wierszu i kolumnie (oddzielnie),
   * policz średnią różnicę bezwzględną dla wartości w powyższym punkcie względem wartości 0 (to jest wartość oczekiwana przy naszych założeniach rozkładu normalnego) - oddzielnie dla średniej z kolumn i średniej z wierszy, pamiętam o tym, że operacje na tablicy numpy wykonywane są w trybie broadcast.

9. Stwórz tablicę o wymiarach 1000x1000 uzupełniając ją wartościami losowymi z rozkładu normalnego standardowego, a następnie posiłkując się przykładami z labów poprzednich (moduł `timeit`) porównaj czasy wykonania dla tej tablicy:
    * zapisu do pliku tekstowego vs. zapis do pliku w formacie picle vs. zapis do pliku skompresowanego (funkcja `savez_compressed` w dokumentacji biblioteki numpy)
    * odczytu dla trzech wyżej wymienionych plików.

In [57]:
import pickle
import timeit

#1

a_small_one = np.arange(1, 65).reshape(8, 8)
print("a_small_one:\n", a_small_one)

#2

print("\nSuma kolumn:")
print(np.sum(a_small_one, axis=0))
print("\nSuma skumulowana wierszy:")
print(np.cumsum(a_small_one, axis=1))
print("\nŚrednia każdego wiersza:")
print(np.mean(a_small_one, axis=1))

#3

even_elements = a_small_one[a_small_one % 2 == 0]
print("\nElementy parzyste:")
print(even_elements)

#4

no_even_small_one = a_small_one.astype(float)
no_even_small_one[no_even_small_one % 2 == 0] = np.nan

#5

print("\nno_even_small_one:\n", no_even_small_one)
print("\nSuma każdego wiersza (nan):")
print(np.nansum(no_even_small_one, axis=1))
print("\nŚrednia każdej kolumny (nan):")
print(np.nanmean(no_even_small_one, axis=0))
print("\nNajmniejsza wartość:")
print(np.nanmin(no_even_small_one))

#6

filled_ones = np.where(np.isnan(no_even_small_one), 1, no_even_small_one)
print("\nNan zamienione na 1:")
print(filled_ones)

restored = np.where(np.isnan(no_even_small_one), a_small_one, no_even_small_one)
print("\nPrzywrócona tablica:")
print(restored)

#7

sto_by_sto = np.random.randn(100, 100)

mean_rows = np.mean(sto_by_sto, axis=1)
mean_cols = np.mean(sto_by_sto, axis=0)

#8

print("\nŚrednia wierszy:")
print(mean_rows)
print("\nŚrednia kolumn:")
print(mean_cols)

mad_rows = np.mean(np.abs(mean_rows - 0))
mad_cols = np.mean(np.abs(mean_cols - 0))

print("\nŚrednia różnica bezwzględna (wiersze):", mad_rows)
print("Średnia różnica bezwzględna (kolumny):", mad_cols)

#9

big = np.random.randn(1000, 1000)

# ---------- zapis ----------

def save_txt():
    np.savetxt("big.txt", big)

def save_pickle():
    with open("big.pkl", "wb") as f:
        pickle.dump(big, f)

def save_npz():
    np.savez_compressed("big_compressed.npz", big)

print("\nCZASY ZAPISU")
print("txt:", timeit.timeit(save_txt, number=1))
print("pickle:", timeit.timeit(save_pickle, number=1))
print("compressed:", timeit.timeit(save_npz, number=1))


# ---------- odczyt ----------

def load_txt():
    np.loadtxt("big.txt")

def load_pickle():
    with open("big.pkl", "rb") as f:
        pickle.load(f)

def load_npz():
    np.load("big_compressed.npz")

print("\nCZASY ODCZYTU")
print("txt:", timeit.timeit(load_txt, number=1))
print("pickle:", timeit.timeit(load_pickle, number=1))
print("compressed:", timeit.timeit(load_npz, number=1))

a_small_one:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]

Suma kolumn:
[232 240 248 256 264 272 280 288]

Suma skumulowana wierszy:
[[  1   3   6  10  15  21  28  36]
 [  9  19  30  42  55  69  84 100]
 [ 17  35  54  74  95 117 140 164]
 [ 25  51  78 106 135 165 196 228]
 [ 33  67 102 138 175 213 252 292]
 [ 41  83 126 170 215 261 308 356]
 [ 49  99 150 202 255 309 364 420]
 [ 57 115 174 234 295 357 420 484]]

Średnia każdego wiersza:
[ 4.5 12.5 20.5 28.5 36.5 44.5 52.5 60.5]

Elementy parzyste:
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64]

no_even_small_one:
 [[ 1. nan  3. nan  5. nan  7. nan]
 [ 9. nan 11. nan 13. nan 15. nan]
 [17. nan 19. nan 21. nan 23. nan]
 [25. nan 27. nan 29. nan 31. nan]
 [33. nan 35. nan 37. nan 39. nan]
 [41. nan 43. nan 45. nan 47. 

/tmp/ipykernel_471/3084273005.py:35: RuntimeWarning: Mean of empty slice
  print(np.nanmean(no_even_small_one, axis=0))


txt: 0.9530243399999563
pickle: 0.008293916999946305
compressed: 0.46146512999996503

CZASY ODCZYTU
txt: 0.48752006500001244
pickle: 0.0024046989999533253
compressed: 0.000262638999970477
